"""
EVOLUTIONARY TRADING ALGO  //  brain
========================
Higher-order intelligence. Regime detection, RL agent, multi-agent consensus,
Financial Jarvis context loop, rationale mining.
The system that watches the systems.
"""

from eta_engine.brain.jarvis_admin import (
    ActionRequest,
    ActionResponse,
    ActionType,
    JarvisAdmin,
    SubsystemId,
    Verdict,
    evaluate_request,
    make_action_request,
)
from eta_engine.brain.jarvis_context import (
    ActionSuggestion,
    AlertLevel,
    EquitySnapshot,
    JarvisAlert,
    JarvisContext,
    JarvisContextBuilder,
    JarvisContextEngine,
    JarvisMargins,
    JarvisMemory,
    JarvisSuggestion,
    JournalSnapshot,
    MacroSnapshot,
    RegimeSnapshot,
    SessionPhase,
    SizingHint,
    StressComponent,
    StressScore,
    Trajectory,
    TrajectoryState,
    build_explanation,
    build_playbook,
    build_snapshot,
    compute_margins,
    compute_session_phase,
    compute_sizing_hint,
    compute_stress_score,
    detect_alerts,
    suggest_action,
)
from eta_engine.brain.multi_agent import (
    AgentMessage,
    AgentRole,
    MultiAgentOrchestrator,
)
from eta_engine.brain.rationale_miner import (
    Cluster,
    MiningReport,
    RationaleMiner,
    RationaleRecord,
    coverage,
    phrase_frequency,
    tokenize_rationale,
    winners_minus_losers,
)
from eta_engine.brain.regime import (
    RegimeAxes,
    RegimeType,
    classify_regime,
    detect_drift,
)
from eta_engine.brain.rl_agent import (
    RLAction,
    RLAgent,
    RLState,
)

__all__ = [
    "ActionRequest",
    "ActionResponse",
    "ActionSuggestion",
    "ActionType",
    "AgentMessage",
    "AgentRole",
    "AlertLevel",
    "Cluster",
    "EquitySnapshot",
    "JarvisAdmin",
    "JarvisAlert",
    "JarvisContext",
    "JarvisContextBuilder",
    "JarvisContextEngine",
    "JarvisMargins",
    "JarvisMemory",
    "JarvisSuggestion",
    "JournalSnapshot",
    "MacroSnapshot",
    "MiningReport",
    "MultiAgentOrchestrator",
    "RLAction",
    "RLAgent",
    "RLState",
    "RationaleMiner",
    "RationaleRecord",
    "RegimeAxes",
    "RegimeSnapshot",
    "RegimeType",
    "SessionPhase",
    "SizingHint",
    "StressComponent",
    "StressScore",
    "SubsystemId",
    "Trajectory",
    "TrajectoryState",
    "Verdict",
    "build_explanation",
    "build_playbook",
    "build_snapshot",
    "classify_regime",
    "compute_margins",
    "compute_session_phase",
    "compute_sizing_hint",
    "compute_stress_score",
    "coverage",
    "detect_alerts",
    "detect_drift",
    "evaluate_request",
    "make_action_request",
    "phrase_frequency",
    "suggest_action",
    "tokenize_rationale",
    "winners_minus_losers",
]
